### ISSUE TITLE
BUG: About Alkemy - Core Values Text has the wrong font family

### ISSUE THREAD

**Issue by jferragut** [jferragut/alkemy#65]
**Issue:**
Due to the font-awesome bullet styling, we have the wrong font-family on the `<li>`'s. The font-family should be the same as the rest of the site.

**Tasks:**
- [x] wrap the text in the `<li>`s within `span` tags
- [x] create css selector that targets `.aboutValues .coreValues span` and changes the font-family

**Acceptance Criteria:**
- [x] Font-family should look the same as the rest of the page

**Comment by jferragut** [comment]
PR approved. Closing issue.
