### ISSUE TITLE
BUG: Build Your Dream Form fields aren't all the same height

### ISSUE THREAD

**Issue by jferragut** [jferragut/alkemy#66]
**Issue:**
If you take a look at the Build Your Dream form on the Responsive Web Design Page, you will notice that:

- the telephone field isn't the same height as the other two fields on step 1.
- on step 4, the text field is smaller than the dropdowns
- also step 4, the text area needs more padding (let's give the text breathing room)

**Tasks:**
- [x] Make sure the input fields and selects are all the same height
- [x] Make sure the text area has adequate padding

**Acceptance Criteria:**
- [ ] Input Fields and selects have same height
- [ ] Text Area on Step 4 has adequate padding and margin-top/bottom

**Comment by h-shams** [comment]
@jferragut ,
May I start working on this?

**Comment by jferragut** [comment]
@h-shams sure man. Create a new branch and give it a shot. When you're done, let me know and I'll review the PR. 

All of our CSS is done in the Scss file and then compiled to CSS after. I am available if you have questions.

**Comment by jferragut** [comment]
@h-shams haven't heard back from you. Circling back around to see if you are working on this issue.

**Comment by h-shams** [comment]
@jferragut sorry about my silence, I send a PR please review it.

**Comment by jferragut** [comment]
@h-shams hey man, no prob. I just reviewed the PR. I'll keep discussing changes there.

**Comment by jferragut** [comment]
Issues addressed in PR #75
