### ISSUE TITLE
BUG: For blog cards on homepage, overlay description needs truncation

### ISSUE THREAD

**Issue by jferragut** [jferragut/alkemy#71]
**Issue:**
On the Homepage, the recent blog cards overlays display a description text for the blog. This text extends beyond the box and is being clipped but incorrectly and passes under the button.

**Reproduction:**
- On homepage, scroll to Recent Blogs
- hover over cards
- Text on some cards doesn't truncate and passes outside of card boundaries.

**Proposed Resolution:**
We need to truncate the excerpt text on the BlogWidget component. Truncation should end with an ellipsis (ie. `...`).

**Tasks:**
- [ ] Truncate excerpt

**Acceptance Criteria:**
- [ ] Homepage Blog Cards should have truncated text
- [ ] Truncated text should end in Ellipsis 
- [ ] Text should not go beyond or under the button on desktop
- [ ] Card should have the appropriate spacing between text and button

**Notes:**
- Clone locally
- Create a new branch for fix
- When done, push changes to branch on this repo
- Create PR noting what was adjusted.

**Comment by jferragut** [comment]
Issue is visible at large breakpoint predominantly. (1024px - 1570px-ish)

**Screenshot of issue:**

![Screen Shot 2019-10-24 at 2 39 56 PM](https://user-images.githubusercontent.com/31458614/67515213-39e94300-f66c-11e9-8787-18f4daea3cb0.png)

**Comment by jferragut** [comment]
Fixed in recent PR. Closing issue as resolved.
