### ISSUE TITLE
Feature Request: Add upcity badge to footer

### ISSUE THREAD

**Issue by jferragut** [jferragut/alkemy#82]
**Issue:**
We have a profile on UpCity, but have not added the badge to our site. 

**Tasks**
- [ ] To add the badge, we need to add specific code to the footer.
```html
<a href="https://upcity.com/local-marketing-agencies/profiles/alkemy-inc/locations/alkemy-inc" target="_blank" rel="noopener" rel="noreferrer">
	<img src="https://app.upcity.com/images/badges/featured.png" width="300px" height="70px"/>
</a>
```

**Acceptance Criteria:**
- [ ] Badge needs to be visible in footer
- [ ] Badge should not negatively impact the design

**Comment by lucasaraujo45** [comment]
I would like to work on this one @jferragut

**Comment by jferragut** [comment]
This issue is completed. Closing out.
